name: loan_ci_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas==2.0.3
    - numpy==1.24.3
    - scikit-learn==1.3.0
    - matplotlib==3.7.2
    - mlflow==2.19.0
